services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .prod.env
    volumes:
      - sober_data:/db
    ports:
      - "8080:8080"
    depends_on:
      init-db:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./sober-ui
      dockerfile: Dockerfile
    env_file:
      - .prod.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s



  # Add init service to create directory and database file
  init-db:
    image: golang:1.22-alpine
    volumes:
      - sober_data:/db
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache curl gcc musl-dev &&
      CGO_ENABLED=1 go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest &&
      echo 'Starting database migration...' &&
      migrate -source file:///app/db/migrations -database sqlite3:///db/sober.db up &&
      echo 'Database migration completed successfully'
      "
    restart: "no"

volumes:
  sober_data:
    driver: local

networks:
  default:
    driver: bridge
  